### ISSUE TITLE
Criar Análise de custos

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/fretz-freedom#11]
Elaborar um documento sobre o custo para desenvolver o projeto.
Usar excel para detalhamento de cada item com seu determinado custo.

- produção
- testes
- publicidade
- implantação
- treinamento
- manutenção.

**Comment by aidnasc** [comment]
Apresentação dos custos do projeto + detalhes:

[https://drive.google.com/open?id=17gkZklKXTRUzb42eEOYfELfTmZabI_Pk_a8ZxP-xt84](url)
