### ISSUE TITLE
Definir forma de venda e divulgação

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/fretz-freedom#15]
Preencher o documento principal com a forma de venda e divulgação discutida entre os responsáveis pelo projeto.

**Comment by aidnasc** [comment]
Atendido junto ao documento de custos do projeto:

[https://drive.google.com/open?id=17gkZklKXTRUzb42eEOYfELfTmZabI_Pk_a8ZxP-xt84](url)
