### ISSUE TITLE
Criar projeto de publicidade do produto

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/fretz-freedom#17]
Definir a forma como o projeto será divulgado, apostar em diferenciais que o destaquem. Analisar o melhor momento e a melhor abordagem para com o público.

**Comment by aidnasc** [comment]
Atendido junto ao documento de custos do projeto:

[https://drive.google.com/open?id=17gkZklKXTRUzb42eEOYfELfTmZabI_Pk_a8ZxP-xt84](url)
